kind: pipeline
type: kubernetes
name: default
steps:
- name: test and package
  image: maven:3-jdk-11
  commands:
    - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    - mvn test -B
    - mvn -B -DskipTests package
